all:
	@cd hsmProxy;make
	@cd se;make
	@cd tokenClient;make
	@cd tokenServer;make
	@cd gateway;make

clean:
	@cd hsmProxy;make clean
	@cd se;make clean
	@cd tokenClient;make clean
	@cd tokenServer;make clean
	@cd gateway;make clean

install:
	@cd hsmProxy;make install
	@cd se;make install
	@cd tokenClient;make install
	@cd tokenServer;make install
	@cd gateway;make install
